[theme]
base="light"
primaryColor="#4d1f00"
backgroundColor="#803300"
secondaryBackgroundColor="#ff8533"
textColor="#FFFFFF"
font="sans serif"

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
#maxMessageSize = 400